// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1IarfQZ5Ca0yVZXjQcwtTIpYzBwxx1A8',
    appId: '1:797667396516:web:0a252a87c2e3a84c940f31',
    messagingSenderId: '797667396516',
    projectId: 'fir-notes-db597',
    authDomain: 'fir-notes-db597.firebaseapp.com',
    storageBucket: 'fir-notes-db597.firebasestorage.app',
    measurementId: 'G-K1GC1X6HS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHt0GhDSCopSwyvJPu30LP1r76Rjz5x3s',
    appId: '1:797667396516:android:3b1d7975f458500a940f31',
    messagingSenderId: '797667396516',
    projectId: 'fir-notes-db597',
    storageBucket: 'fir-notes-db597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLxG7wIoY-V5AxLRQnXlnmxDKlB1-Bg0',
    appId: '1:797667396516:ios:2552325378d90946940f31',
    messagingSenderId: '797667396516',
    projectId: 'fir-notes-db597',
    storageBucket: 'fir-notes-db597.firebasestorage.app',
    iosBundleId: 'com.example.firebasenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwLxG7wIoY-V5AxLRQnXlnmxDKlB1-Bg0',
    appId: '1:797667396516:ios:2552325378d90946940f31',
    messagingSenderId: '797667396516',
    projectId: 'fir-notes-db597',
    storageBucket: 'fir-notes-db597.firebasestorage.app',
    iosBundleId: 'com.example.firebasenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1IarfQZ5Ca0yVZXjQcwtTIpYzBwxx1A8',
    appId: '1:797667396516:web:db03b5903f95c695940f31',
    messagingSenderId: '797667396516',
    projectId: 'fir-notes-db597',
    authDomain: 'fir-notes-db597.firebaseapp.com',
    storageBucket: 'fir-notes-db597.firebasestorage.app',
    measurementId: 'G-TGV1X5ZKZ0',
  );
}
